# Generated by Django 5.0.6 on 2026-05-21 06:26

from django.db import migrations, models


def migrate_roles_forward(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='EMP').update(role='NEW')
    User.objects.filter(is_superuser=True).update(role='ADM')


def migrate_roles_backward(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='NEW').update(role='EMP')
    User.objects.filter(role='ADM', is_superuser=True).update(role='HR')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADM', 'Админ'), ('HR', 'HR-менеджер'), ('MGR', 'Руководитель'), ('NEW', 'Новый сотрудник')], default='NEW', max_length=3, verbose_name='Роль'),
        ),
    ]
