# Generated by Django 5.0.6 on 2026-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено')], default='IN_PROGRESS', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Адаптация сотрудника',
                'verbose_name_plural': 'Адаптации сотрудников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Программа адаптации',
                'verbose_name_plural': 'Программы адаптации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название шага')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content_type', models.CharField(choices=[('TEXT', 'Текст'), ('VIDEO', 'Видео'), ('QUIZ', 'Тест'), ('TASK', 'Задание')], default='TEXT', max_length=10, verbose_name='Тип контента')),
                ('content', models.JSONField(default=dict, verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='Дней на выполнение')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
            ],
            options={
                'verbose_name': 'Шаг адаптации',
                'verbose_name_plural': 'Шаги адаптации',
                'ordering': ['program', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Не начато'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Выполнено')], default='NOT_STARTED', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки сотрудника')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
            ],
            options={
                'verbose_name': 'Прогресс по шагу',
                'verbose_name_plural': 'Прогресс по шагам',
            },
        ),
    ]
