# Generated by Django 5.0.6 on 2026-05-21 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeonboarding',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboardings', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='employeeonboarding',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMP'}, on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='onboardingprogram',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'HR'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='employeeonboarding',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_onboardings', to='onboarding.onboardingprogram', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onboarding.onboardingprogram', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='stepprogress',
            name='employee_onboarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progresses', to='onboarding.employeeonboarding', verbose_name='Программа адаптации'),
        ),
        migrations.AddField(
            model_name='stepprogress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='onboarding.onboardingstep', verbose_name='Шаг'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingstep',
            unique_together={('program', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='stepprogress',
            unique_together={('employee_onboarding', 'step')},
        ),
    ]
