# Generated by Django 5.0.6 on 2026-05-21 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeonboarding',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'NEW'}, on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='onboardingprogram',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['HR', 'ADM', 'MGR']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
